name: Build and Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          artifacts: app/build/outputs/apk/debug/app-debug.apk
          token: ${{ secrets.GITHUB_TOKEN }}
